"""Exporter - zip project export for generated pipeline code."""

import os
import io
import json
import zipfile
from typing import Optional


def export_pipeline_zip(
    stage_codes: dict[str, str],
    pipeline_config: dict,
    project_name: str = "ml_pipeline",
    include_readme: bool = True,
    include_runner: bool = True,
) -> bytes:
    """Bundle generated pipeline into a downloadable .zip file.

    Creates a zip containing:
    - Generated Python scripts for each stage
    - README.md with pipeline documentation
    - requirements.txt for the generated project
    - run_pipeline.sh shell script to execute all stages
    - pipeline_config.json with the configuration used

    Parameters
    ----------
    stage_codes : dict
        Mapping of stage_name -> generated Python code.
    pipeline_config : dict
        Pipeline configuration dictionary.
    project_name : str
        Name for the project directory inside the zip.
    include_readme : bool
        Whether to include a README.md.
    include_runner : bool
        Whether to include run_pipeline.sh.

    Returns
    -------
    bytes
        Zip file content as bytes.
    """
    buffer = io.BytesIO()

    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # Write stage scripts
        for stage_name, code in stage_codes.items():
            filepath = f"{project_name}/stages/{stage_name}.py"
            zf.writestr(filepath, code)

        # Write pipeline config
        config_json = json.dumps(pipeline_config, indent=2, default=str)
        zf.writestr(f"{project_name}/pipeline_config.json", config_json)

        # Write requirements.txt for the generated project
        requirements = _generate_requirements(pipeline_config)
        zf.writestr(f"{project_name}/requirements.txt", requirements)

        # Write README.md
        if include_readme:
            readme = _generate_readme(pipeline_config, list(stage_codes.keys()))
            zf.writestr(f"{project_name}/README.md", readme)

        # Write run_pipeline.sh
        if include_runner:
            runner = _generate_runner(list(stage_codes.keys()))
            zf.writestr(f"{project_name}/run_pipeline.sh", runner)

        # Write __init__.py for stages package
        zf.writestr(f"{project_name}/stages/__init__.py", "")

    return buffer.getvalue()


def _generate_requirements(pipeline_config: dict) -> str:
    """Generate requirements.txt for the exported pipeline."""
    modality = pipeline_config.get("modality", "EEG")
    model = pipeline_config.get("model", "cnn1d")

    deps = [
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "scikit-learn>=1.3.0",
        "pandas>=2.0.0",
        "matplotlib>=3.7.0",
        "torch>=2.0.0",
    ]

    if modality == "EEG":
        deps.append("mne>=1.5.0")
    elif modality == "ECG":
        deps.extend(["wfdb>=4.1.0", "neurokit2>=0.2.7"])

    if model == "gat_tcn":
        deps.append("torch-geometric>=2.4.0")

    deps.extend(["shap>=0.43.0", "captum>=0.6.0"])

    return "\n".join(sorted(deps)) + "\n"


def _generate_readme(pipeline_config: dict, stages: list[str]) -> str:
    """Generate README.md for the exported pipeline."""
    modality = pipeline_config.get("modality", "EEG")
    task = pipeline_config.get("task", "classification")
    model = pipeline_config.get("model", "cnn1d")
    dataset = pipeline_config.get("dataset", "Unknown")

    readme = f"""# {modality} ML Pipeline - {task}

Auto-generated by NeuroPipeline.

## Configuration

- **Modality**: {modality}
- **Task**: {task}
- **Model**: {model}
- **Dataset**: {dataset}

## Pipeline Stages

"""
    for i, stage in enumerate(stages, 1):
        readme += f"{i}. `{stage}.py`\n"

    readme += """
## Usage

```bash
# Install dependencies
pip install -r requirements.txt

# Run the full pipeline
bash run_pipeline.sh

# Or run individual stages
python stages/<stage_name>.py
```

## Configuration

Edit `pipeline_config.json` to customize pipeline parameters.
"""
    return readme


def _generate_runner(stages: list[str]) -> str:
    """Generate run_pipeline.sh shell script."""
    lines = [
        "#!/bin/bash",
        "# Auto-generated pipeline runner",
        "set -e",
        "",
        'echo "Starting ML Pipeline..."',
        "",
    ]

    for stage in stages:
        lines.append(f'echo "Running: {stage}"')
        lines.append(f"python stages/{stage}.py")
        lines.append("")

    lines.append('echo "Pipeline complete!"')
    return "\n".join(lines) + "\n"
