"""Landing page for NeuroPipeline - dataset upload and pipeline initialization."""

import json


def render_landing():
    """Render the landing screen with file upload and dataset summary.

    Provides:
    - JSON file uploader for Agent 1 inspection reports
    - Raw dataset upload option
    - Dataset summary card after loading
    - Build Pipeline button to trigger pipeline planning
    """
    import streamlit as st

    st.markdown(
        '<h1 style="text-align: center;">Welcome to NeuroPipeline</h1>',
        unsafe_allow_html=True,
    )
    st.markdown(
        '<p style="text-align: center; color: #64748b;">'
        "Upload an Agent 1 inspection report or a raw dataset to begin building "
        "your ML pipeline.</p>",
        unsafe_allow_html=True,
    )

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("#### Agent 1 Inspection Report")
        uploaded_json = st.file_uploader(
            "Upload JSON report from NeuroInspect",
            type=["json"],
            key="json_uploader",
            help="Upload the .json inspection report generated by Agent 1",
        )

    with col2:
        st.markdown("#### Raw Dataset")
        uploaded_raw = st.file_uploader(
            "Upload raw EEG/ECG dataset",
            type=["edf", "bdf", "set", "csv", "mat", "dat", "hea"],
            key="raw_uploader",
            help="Upload a raw dataset file to trigger Agent 1 inspection first",
        )

    # Process uploaded JSON report
    if uploaded_json is not None:
        try:
            report_data = json.loads(uploaded_json.read().decode("utf-8"))
            st.session_state["inspection_report"] = report_data
            _render_dataset_summary(report_data)
        except (json.JSONDecodeError, UnicodeDecodeError):
            st.error("Invalid JSON file. Please upload a valid inspection report.")

    elif uploaded_raw is not None:
        st.info(
            "Raw dataset uploaded. In production this would trigger "
            "Agent 1 inspection. For now, please upload the JSON report."
        )

    # Show Build Pipeline button if report is loaded
    if st.session_state.get("inspection_report"):
        st.markdown("---")
        if st.button("Build Pipeline", type="primary", use_container_width=True):
            st.session_state["current_screen"] = "canvas"
            st.rerun()


def _render_dataset_summary(report_data):
    """Render a dataset summary card from the inspection report.

    Args:
        report_data: Dictionary containing the Agent 1 inspection report.
    """
    import streamlit as st

    metadata = report_data.get("metadata", {})
    modality = report_data.get("modality", "Unknown")
    dataset_name = metadata.get("dataset_name", report_data.get("known_dataset", "Unknown"))
    channels = metadata.get("n_channels", "N/A")
    quality_score = report_data.get("quality_score", "N/A")
    recommended_model = report_data.get("recommended_model", "auto")

    summary_html = f"""
<div class="dataset-summary">
    <div class="summary-title">Dataset Summary</div>
    <div class="summary-row">
        <span class="summary-key">Dataset</span>
        <span class="summary-value">{dataset_name}</span>
    </div>
    <div class="summary-row">
        <span class="summary-key">Modality</span>
        <span class="summary-value">{modality.upper()}</span>
    </div>
    <div class="summary-row">
        <span class="summary-key">Channels</span>
        <span class="summary-value">{channels}</span>
    </div>
    <div class="summary-row">
        <span class="summary-key">Quality Score</span>
        <span class="summary-value">{quality_score}</span>
    </div>
    <div class="summary-row">
        <span class="summary-key">Recommended Model</span>
        <span class="summary-value">{recommended_model}</span>
    </div>
</div>
"""
    st.markdown(summary_html, unsafe_allow_html=True)
