"""Code Generator - Anthropic Claude API + Jinja2 template rendering."""

import os
import sys
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from config import (
    ANTHROPIC_API_KEY,
    ANTHROPIC_MODEL,
    ANTHROPIC_MAX_TOKENS,
    CODE_GEN_SYSTEM_PROMPT,
    TEMPLATE_REGISTRY,
)


def generate_stage_code(stage_name: str, config: dict, dataset_info: dict) -> str:
    """Generate Python code for a pipeline stage using templates.

    Attempts to use Jinja2 templates first. Falls back to inline code
    generation if template is not available.

    Parameters
    ----------
    stage_name : str
        Name of the pipeline stage (e.g., 'eeg_quality_check').
    config : dict
        Stage-specific configuration parameters.
    dataset_info : dict
        Dataset information from Agent 1 report.

    Returns
    -------
    str
        Generated Python code for the stage.
    """
    template_path = TEMPLATE_REGISTRY.get(stage_name)

    if template_path:
        # Try Jinja2 template rendering
        code = _render_template(template_path, config, dataset_info)
        if code:
            return code

    # Fall back to generating code from config
    return _generate_from_config(stage_name, config, dataset_info)


def generate_custom_model(description: str, dataset_info: dict) -> str:
    """Generate a custom model architecture via Claude API.

    Parameters
    ----------
    description : str
        Natural language description of the desired model architecture.
    dataset_info : dict
        Dataset information to inform the model design.

    Returns
    -------
    str
        Generated PyTorch model code.
    """
    prompt = _build_model_prompt(description, dataset_info)
    return _call_claude_api(prompt)


def _render_template(template_path: str, config: dict, dataset_info: dict) -> Optional[str]:
    """Render a Jinja2 template with the given config.

    Parameters
    ----------
    template_path : str
        Relative path to the template file.
    config : dict
        Configuration parameters for the template.
    dataset_info : dict
        Dataset information.

    Returns
    -------
    str or None
        Rendered code, or None if template not found.
    """
    try:
        from jinja2 import Environment, FileSystemLoader

        template_dir = os.path.join(os.path.dirname(__file__), "..", "templates")
        if not os.path.isdir(template_dir):
            return None

        # Get relative template path within templates directory
        rel_path = template_path.replace("templates/", "", 1)
        template_file = os.path.join(template_dir, rel_path)

        if not os.path.exists(template_file):
            return None

        env = Environment(
            loader=FileSystemLoader(template_dir),
            trim_blocks=True,
            lstrip_blocks=True,
        )
        template = env.get_template(rel_path)
        return template.render(config=config, dataset_info=dataset_info)

    except ImportError:
        return None
    except Exception:
        return None


def _generate_from_config(stage_name: str, config: dict, dataset_info: dict) -> str:
    """Generate code directly from configuration (no template).

    Parameters
    ----------
    stage_name : str
        Name of the pipeline stage.
    config : dict
        Stage-specific configuration.
    dataset_info : dict
        Dataset information.

    Returns
    -------
    str
        Generated Python code string.
    """
    modality = dataset_info.get("modality", "EEG")
    dataset = dataset_info.get("dataset", "unknown")

    header = f'''"""
Pipeline Stage: {stage_name}
Modality: {modality}
Dataset: {dataset}
Auto-generated by NeuroPipeline
"""

import numpy as np
import logging

logger = logging.getLogger(__name__)

'''
    body = f"# Configuration\nCONFIG = {repr(config)}\n\n"
    body += f"# Dataset info\nDATASET_INFO = {repr(dataset_info)}\n\n"
    body += f"""
def run(data, config=None):
    \"\"\"Execute {stage_name} stage.\"\"\"
    if config is None:
        config = CONFIG
    logger.info("Running stage: {stage_name}")
    # Stage implementation will be rendered from templates
    return data
"""

    return header + body


def _build_model_prompt(description: str, dataset_info: dict) -> str:
    """Build the prompt for custom model generation.

    Parameters
    ----------
    description : str
        User's description of desired model.
    dataset_info : dict
        Dataset context.

    Returns
    -------
    str
        Complete prompt for Claude API.
    """
    modality = dataset_info.get("modality", "EEG")
    n_channels = dataset_info.get("n_channels", 14)
    n_classes = len(dataset_info.get("labels", [2]))
    fs = dataset_info.get("sampling_rate", 128)

    prompt = f"""Generate a complete PyTorch model class for the following:

Description: {description}

Context:
- Modality: {modality}
- Number of input channels: {n_channels}
- Number of output classes: {n_classes}
- Sampling rate: {fs} Hz

Requirements:
- Define as a PyTorch nn.Module subclass
- Include forward() method with proper input/output shapes documented
- Add weight initialization
- Include a get_model_summary() helper function
- The model should handle input shape: (batch_size, n_channels, sequence_length)
- Output shape: (batch_size, n_classes)

Return ONLY the Python code, no explanations."""

    return prompt


def _call_claude_api(prompt: str) -> str:
    """Call the Anthropic Claude API for code generation.

    Parameters
    ----------
    prompt : str
        The prompt to send to Claude.

    Returns
    -------
    str
        Generated code from Claude.
    """
    try:
        from anthropic import Anthropic

        client = Anthropic(api_key=ANTHROPIC_API_KEY)
        message = client.messages.create(
            model=ANTHROPIC_MODEL,
            max_tokens=ANTHROPIC_MAX_TOKENS,
            system=CODE_GEN_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        # Extract text from response
        response_text = ""
        for block in message.content:
            if hasattr(block, "text"):
                response_text += block.text

        # Extract code block if present
        if "```python" in response_text:
            code_start = response_text.index("```python") + len("```python")
            code_end = response_text.index("```", code_start)
            return response_text[code_start:code_end].strip()
        elif "```" in response_text:
            code_start = response_text.index("```") + 3
            code_end = response_text.index("```", code_start)
            return response_text[code_start:code_end].strip()

        return response_text.strip()

    except ImportError:
        return _fallback_model_code(prompt)
    except Exception as e:
        return f"# Error calling Claude API: {e}\n# Falling back to template\n" + _fallback_model_code(prompt)


def _fallback_model_code(prompt: str) -> str:
    """Generate fallback model code when API is unavailable."""
    return '''"""Custom model - API generation unavailable, using template."""

import torch
import torch.nn as nn


class CustomModel(nn.Module):
    """Custom model architecture."""

    def __init__(self, n_channels=14, n_classes=3, seq_length=128):
        super().__init__()
        self.conv1 = nn.Conv1d(n_channels, 64, kernel_size=7, padding=3)
        self.bn1 = nn.BatchNorm1d(64)
        self.conv2 = nn.Conv1d(64, 128, kernel_size=5, padding=2)
        self.bn2 = nn.BatchNorm1d(128)
        self.pool = nn.AdaptiveAvgPool1d(1)
        self.fc = nn.Linear(128, n_classes)
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv1d):
                nn.init.kaiming_normal_(m.weight)
            elif isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight)

    def forward(self, x):
        """Forward pass. Input: (batch, channels, seq_len) -> Output: (batch, n_classes)"""
        x = torch.relu(self.bn1(self.conv1(x)))
        x = torch.relu(self.bn2(self.conv2(x)))
        x = self.pool(x).squeeze(-1)
        return self.fc(x)


def get_model_summary(model, input_shape=(1, 14, 128)):
    """Print model summary."""
    from torchinfo import summary
    return summary(model, input_size=input_shape)
'''
